const { test } = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');
const fs = require('node:fs');
const path = require('node:path');
async function app(stored = {}) {
  const html = fs.readFileSync('index.html','utf8');
  const dom = new JSDOM(html,{url:'https://timestudy.moteops.tech/',runScripts:'dangerously'});
  const w=dom.window; w.eval=code=>require('node:vm').runInContext(code,dom.getInternalVMContext());
  w.alert=()=>{};w.confirm=()=>true;w.scrollTo=()=>{};
  Object.entries(stored).forEach(([k,v])=>w.localStorage.setItem(k,JSON.stringify(v)));
  w.fetch=async url=>{ const name=String(url).split('?')[0]; const data=fs.readFileSync(name); return {ok:true,json:async()=>JSON.parse(data),arrayBuffer:async()=>new w.Uint8Array(data).buffer}; };
  w.eval(fs.readFileSync(require.resolve('pdf-lib/dist/pdf-lib.min.js'),'utf8'));
  const code=fs.existsSync('app.js')?fs.readFileSync('app.js','utf8'):Array.from(html.matchAll(/<script>([\s\S]*?)<\/script>/g)).map(x=>x[1]).join('\n');
  w.eval(code);
  if(fs.existsSync('assets/ical.min.js'))w.eval(fs.readFileSync('assets/ical.min.js','utf8'));
  if(fs.existsSync('calendar.js'))w.eval(fs.readFileSync('calendar.js','utf8'));
  await new Promise(r=>setTimeout(r,20));
  return w;
}
function seed(w) {
  w.eval(`applyPeriod('2026-09-24'); S.hours=blank(); S.reviewed={}; S.paid={}; S.off={}; CONFIG.days.forEach(D=>{S.reviewed[D.d]=true;S.paid[D.d]=D.d===1?'10':'0';S.off[D.d]=D.d!==1;}); S.hours[1]['1']=[{h:'10',c:'12345'}];`);
  for(const [id,v] of Object.entries({p_last:'Example',p_first:'Test',p_emp:'TEST-ONLY',p_fac:'AHS',p_dept:'Emergency',p_job:'PA',p_hpw:'10',p_phone:'555-0100',cc_er:'12345'}))w.document.getElementById(id).value=v;
}
test('fresh colleague opens the September study, not an expired quarter',async()=>{const w=await app();assert.equal(w.eval('CONFIG.days[0].date'),'2026-09-24');w.close();});
test('colleague link never copies provider identity or calendar credentials',async()=>{const w=await app();seed(w);let copied='';w.navigator.clipboard={writeText:async s=>{copied=s;}};w.copyLink();await Promise.resolve();const u=new URL(copied);assert.equal(u.searchParams.get('first'),null);assert.equal(u.searchParams.get('emp'),null);assert.equal(u.searchParams.get('study'),'2026-09-24');w.close();});
test('a legacy saved signature is not automatically applied to another study',async()=>{const w=await app({pnpp_sig_applied:'old-signature'});assert.ok(!w.eval('S.appliedSig'));w.close();});
test('negative hours block export rather than disappear from the PDF',async()=>{const w=await app();seed(w);w.eval("S.hours[1]['2']=[{h:'-1',c:'12345'}]");await assert.rejects(()=>w.buildPDF(),/hours|quarter|negative|check/i);w.close();});
test('unreviewed zero days cannot silently become days off',async()=>{const w=await app();seed(w);w.eval('S.reviewed[7]=false');await assert.rejects(()=>w.buildPDF(),/review|day|check/i);w.close();});
test('weekly mismatch needs an explanation on the revised form',async()=>{const w=await app();seed(w);w.document.getElementById('p_hpw').value='40';await assert.rejects(()=>w.buildPDF(),/explanation|difference|check/i);w.close();});
test('completed export fills revised shared fields and leaves signature fields unsigned',async()=>{const w=await app();seed(w);const {bytes}=await w.buildPDF();const doc=await w.PDFLib.PDFDocument.load(bytes);const f=doc.getForm();assert.equal(f.getTextField('Employee Number').getText(),'TEST-ONLY');assert.equal(f.getTextField('Department').getText(),'Emergency');assert.equal(f.getTextField('Job Classification/Position').getText(),'PA');assert.equal(f.getTextField('Total Hours Day 1').getText(),'10.00');assert.equal(f.getTextField('Day 7 Date').getText(),'Wednesday September 30, 2026');assert.equal(f.getField('Employee Signature').acroField.dict.has(w.PDFLib.PDFName.of('V')),false);w.close();});
test('overnight shifts split into the two correct calendar days',async()=>{const w=await app();w.document.getElementById('cc_ip').value='12345';w.parseTxtRegex('9/24 3pm to 1am');w.applyShifts();assert.equal(w.eval('dayTotal(1)'),9);assert.equal(w.eval('dayTotal(2)'),1);assert.equal(w.eval('S.reviewed[1]'),undefined);w.close();});
test('out-of-period dates never borrow an earlier valid day',async()=>{const w=await app();w.parseTxtRegex('9/24 7am to 5pm\n10/1 7am to 5pm');assert.equal(w.eval('S.shifts.length'),1);w.close();});
test('invalid clock times never roll into a different date',async()=>{const w=await app();w.parseTxtRegex('9/24 25am to 26pm');assert.equal(w.eval('S.shifts.length'),0);w.close();});
test('each entry must be a quarter-hour even if the total is a quarter-hour',async()=>{const w=await app();seed(w);w.eval("S.hours[1]['1']=[{h:'9.875',c:'12345'}];S.hours[1]['2']=[{h:'.125',c:'12345'}]");await assert.rejects(()=>w.buildPDF(),/check/i);w.close();});
test('editing an already checked day invalidates its confirmation',async()=>{const w=await app();seed(w);w.setH(1,'1',0,'9');assert.equal(w.eval('S.reviewed[1]'),false);w.close();});
test('an explanation is exported into the revised justification field',async()=>{const w=await app();seed(w);w.document.getElementById('p_hpw').value='40';w.document.getElementById('variance').value='Scheduled for fewer shifts.';const {bytes}=await w.buildPDF();const doc=await w.PDFLib.PDFDocument.load(bytes);assert.equal(doc.getForm().getTextField('Justification for "Normal Hours Per Week not matching Total Hours').getText(),'Scheduled for fewer shifts.');if(process.env.QA_OUTPUT)fs.writeFileSync(process.env.QA_OUTPUT,bytes);w.close();});
test('draft survives reopening without restoring old-period data or a signature',async()=>{let w=await app();seed(w);w.saveState();const saved={};for(const k of Object.keys(w.localStorage))saved[k]=JSON.parse(w.localStorage.getItem(k));w.close();w=await app(saved);assert.equal(w.document.getElementById('p_emp').value,'TEST-ONLY');assert.equal(w.eval('dayTotal(1)'),10);assert.ok(!w.eval('S.appliedSig'));w.close();});
test('moving through the shifts step does not overwrite corrected activity hours',async()=>{const w=await app();seed(w);w.eval("S.shifts=[{start:'2026-09-24T07:00:00',end:'2026-09-24T19:00:00',name:'shift',use:true}]");w.go(1);const b=[...w.document.querySelectorAll('#panel1 button')].find(b=>b.textContent.includes('Continue to daily'));b.click();assert.equal(w.eval('dayTotal(1)'),10);w.close();});
test('non-quarter-hour shifts are not silently rounded into reported hours',async()=>{const w=await app();w.parseTxtRegex('9/24 7:10am to 5pm');w.applyShifts();assert.equal(w.eval('dayTotal(1)'),0);w.close();});
test('a partially typed hour is saved before the field loses focus',async()=>{const w=await app();seed(w);w.go(2);const input=w.document.querySelector('[aria-label="00001 hours entry 1"]');input.value='9.5';input.dispatchEvent(new w.Event('input',{bubbles:true}));const draft=JSON.parse(w.localStorage.getItem('pnpp_ts_v2:2026-27|Q1|2026-09-24'));assert.equal(draft.hours[1]['1'][0].h,'9.5');assert.equal(draft.reviewed[1],false);w.close();});
test('a shift beginning the night before the study contributes only in-window hours',async()=>{const w=await app();w.parseTxtRegex('9/23 11pm to 7am');w.applyShifts();assert.equal(w.eval('dayTotal(1)'),7);w.close();});

const calendar=(...events)=>'BEGIN:VCALENDAR\r\nVERSION:2.0\r\n'+events.map((e,i)=>'BEGIN:VEVENT\r\nUID:shift'+i+'\r\n'+e+'\r\nEND:VEVENT\r\n').join('')+'END:VCALENDAR';
test('QGenda requires a private subscription URL on the exact trusted host',async()=>{const w=await app();assert.match(w.validateQGendaURL('webcal://app.qgenda.com/ical?key=TEST'),/^https:/);for(const u of ['https://app.qgenda.com.evil.com/ical?key=X','https://app.qgenda.com/Schedule/id','http://app.qgenda.com/ical?key=X'])assert.throws(()=>w.validateQGendaURL(u));w.close();});
test('QGenda UTC shifts become Pacific hours and one week confirmation replaces seven clicks',async()=>{const w=await app();seed(w);w.eval('S.hours=blank(); S.reviewed={}; S.off={}; S.paid={};');w.document.getElementById('cc_ip').value='12345';const evs=w.parseQGendaICS(calendar('DTSTART:20260924T220000Z\r\nDTEND:20260925T080000Z\r\nSUMMARY:ED shift'));w.ingestShifts(evs);assert.equal(w.applyShifts(),true);assert.equal(w.eval('dayTotal(1)'),9);assert.equal(w.eval('dayTotal(2)'),1);assert.ok(!w.eval('S.reviewed[1]'));w.confirmWeek();assert.ok(w.eval('CONFIG.days.every(D=>S.reviewed[D.d])'));assert.equal(w.eval('S.off[3]'),true);assert.ok(w.checks().every(x=>x.ok));w.close();});
test('all-day QGenda events are not silently converted to paid shifts',async()=>{const w=await app();assert.throws(()=>w.parseQGendaICS(calendar('DTSTART;VALUE=DATE:20260924\r\nDTEND;VALUE=DATE:20260925\r\nSUMMARY:ED')),/all.day/i);w.close();});
test('QGenda honors cancellations, recurrence exclusions and out-of-window events',async()=>{const w=await app();const evs=w.parseQGendaICS(calendar('DTSTART:20260924T140000Z\r\nDTEND:20260924T220000Z\r\nRRULE:FREQ=DAILY;COUNT=3\r\nEXDATE:20260925T140000Z\r\nSUMMARY:ED','DTSTART:20260927T140000Z\r\nDTEND:20260927T220000Z\r\nSTATUS:CANCELLED','DTSTART:20261001T140000Z\r\nDTEND:20261001T220000Z'));assert.equal(evs.length,2);w.close();});
test('failed QGenda import preserves existing hours and does not save the private feed URL',async()=>{const w=await app();seed(w);w.document.getElementById('qgendaurl').value='https://app.qgenda.com/ical?key=PRIVATE_TEST';w.fetch=async()=>{throw new Error('network')};await w.importQGenda();assert.equal(w.eval('dayTotal(1)'),10);assert.ok(!JSON.stringify(w.localStorage).includes('PRIVATE_TEST'));assert.match(w.document.getElementById('qgendastatus').textContent,/could not|unavailable/i);w.close();});
test('previous completed PDF imports only provider details, never hours or signatures',async()=>{const w=await app();seed(w);const {bytes}=await w.buildPDF();w.document.getElementById('p_emp').value='';w.eval('S.hours=blank();S.reviewed={};');const count=await w.importProviderPDF(bytes);assert.ok(count>5);assert.equal(w.document.getElementById('p_emp').value,'TEST-ONLY');assert.equal(w.eval('dayTotal(1)'),0);assert.ok(!w.eval('S.appliedSig'));w.close();});
test('availability blocks are excluded while Pacific TZID assignments remain accurate',async()=>{const w=await app();const evs=w.parseQGendaICS(calendar('DTSTART;VALUE=DATE:20260924\r\nDTEND;VALUE=DATE:20260925\r\nSUMMARY:HGH - Unavailable All Shifts','DTSTART;TZID=America/Los_Angeles:20260924T150000\r\nDTEND;TZID=America/Los_Angeles:20260925T010000\r\nSUMMARY:Swing ED'));assert.equal(evs.length,1);assert.equal(evs[0].start.getHours(),15);assert.equal(evs[0].end.getHours(),1);w.close();});
test('new cancelled event revision supersedes an older active shift',async()=>{const w=await app();const raw=calendar('DTSTART:20260924T140000Z\r\nDTEND:20260924T220000Z\r\nSEQUENCE:0','DTSTART:20260924T140000Z\r\nDTEND:20260924T220000Z\r\nSEQUENCE:1\r\nSTATUS:CANCELLED').replace('UID:shift1','UID:shift0');assert.equal(w.parseQGendaICS(raw).length,0);w.close();});
test('providing the missing default cost center fills imported days without replacing existing allocations',async()=>{const w=await app();seed(w);w.eval("S.hours[2]['1']=[{h:'2',c:''}];S.hours[1]['1'][0].c='OTHER';");w.document.getElementById('cc_ip').value='12345';w.go(3);assert.equal(w.eval("S.hours[2]['1'][0].c"),'12345');assert.equal(w.eval("S.hours[1]['1'][0].c"),'OTHER');w.close();});
test('link import uses the relay, fills the week, clears the key and opens review',async()=>{const w=await app();seed(w);w.document.getElementById('cc_ip').value='12345';w.document.getElementById('qgendaurl').value='https://app.qgenda.com/ical?key=PRIVATE_TEST';let requested;w.fetch=async(url,opts)=>{requested={url,opts};return {ok:true,text:async()=>calendar('DTSTART:20260924T140000Z\r\nDTEND:20260925T000000Z\r\nSUMMARY:ED')}};await w.importQGenda();assert.match(requested.url,/^https:\/\/timestudy-relay\.mikedmote5258\.workers\.dev\/\?url=/);assert.equal(requested.opts.credentials,'omit');assert.equal(w.eval('S.step'),3);assert.equal(w.eval('dayTotal(1)'),10);assert.equal(w.document.getElementById('qgendaurl').value,'');assert.ok(!JSON.stringify(w.localStorage).includes('PRIVATE_TEST'));w.close();});
test('explicit calendar identity and profile fields are reused without inventing weekly hours',async()=>{const w=await app();const evs=w.parseQGendaICS(calendar('DTSTART:20260924T140000Z\r\nDTEND:20260925T000000Z\r\nSUMMARY:ED\r\nDESCRIPTION:Staff: Example\\, Test\\nEmployee Number: TEST-ONLY\\nDepartment: Emergency\\nCost Center: 12345'));w.applyCalendarProfile(evs.profile);assert.equal(w.document.getElementById('p_first').value,'Test');assert.equal(w.document.getElementById('p_last').value,'Example');assert.equal(w.document.getElementById('p_emp').value,'TEST-ONLY');assert.equal(w.document.getElementById('p_hpw').value,'');assert.equal(evs[0].costCenter,'12345');w.close();});
test('an all-day event with an explicit clock range can be prepared without human re-entry',async()=>{const w=await app();const evs=w.parseQGendaICS(calendar('DTSTART;VALUE=DATE:20260924\r\nDTEND;VALUE=DATE:20260925\r\nSUMMARY:Swing ED 3pm-1am'));assert.equal(evs[0].start.getHours(),15);assert.equal(evs[0].end.getDate(),25);assert.equal(evs[0].end.getHours(),1);w.close();});
test('conflicting staff identities reject a shared calendar instead of merging colleagues',async()=>{const w=await app();assert.throws(()=>w.parseQGendaICS(calendar('DTSTART:20260924T140000Z\r\nDTEND:20260924T220000Z\r\nDESCRIPTION:Staff: Example\\, Test','DTSTART:20260925T140000Z\r\nDTEND:20260925T220000Z\r\nDESCRIPTION:Staff: Other\\, Person')),/multiple|personal/i);w.close();});
test('explicit cost centers and activity codes survive automatic preparation',async()=>{const w=await app();const evs=w.parseQGendaICS(calendar('DTSTART:20260924T140000Z\r\nDTEND:20260924T220000Z\r\nDESCRIPTION:Cost Center: 12345\\nActivity Code: 00010'));w.ingestShifts(evs);w.applyShifts();assert.equal(w.eval("S.hours[1]['10'][0].h"),'8.00');assert.equal(w.eval("S.hours[1]['10'][0].c"),'12345');assert.equal(w.eval("S.hours[1]['1'][0].h"),'');w.close();});
test('review asks only for missing fields and applies supplied default center to all shifts',async()=>{const w=await app();seed(w);w.document.getElementById('p_emp').value='';w.go(3);assert.ok(w.document.querySelector('#missingdetails [data-field="p_emp"]'));assert.ok(!w.document.querySelector('#missingdetails [data-field="p_first"]'));w.close();});
test('all-day text timing from the previous evening contributes only study-window hours',async()=>{const w=await app();const evs=w.parseQGendaICS(calendar('DTSTART;VALUE=DATE:20260923\r\nDTEND;VALUE=DATE:20260924\r\nSUMMARY:Night ED 11pm-7am'));w.ingestShifts(evs);w.applyShifts();assert.equal(w.eval('dayTotal(1)'),7);w.close();});
test('different explicit cost centers on one day stay separate',async()=>{const w=await app();w.ingestShifts(w.parseQGendaICS(calendar('DTSTART:20260924T140000Z\r\nDTEND:20260924T180000Z\r\nDESCRIPTION:Cost Center: A','DTSTART:20260924T180000Z\r\nDTEND:20260924T220000Z\r\nDESCRIPTION:Cost Center: B')));w.applyShifts();assert.equal(w.eval("S.hours[1]['1'].length"),2);assert.equal(w.eval("S.hours[1]['1'][1].c"),'B');assert.equal(w.eval('dayTotal(1)'),8);w.close();});
test('Highland ED shifts reuse the previous form setting without asking for a code',async()=>{const w=await app();w.ingestShifts([{start:new Date('2026-09-24T15:00:00'),end:new Date('2026-09-25T01:00:00'),name:'Swing ED Highland APP'}]);w.applyShifts();w.go(3);assert.equal(w.eval("S.hours[1]['1'][0].c"),'17013');assert.equal(w.eval("S.hours[2]['1'][0].c"),'17013');assert.ok(!w.document.querySelector('#missingdetails [data-field^="cc_"]'));w.close();});
test('a recognizable work-location choice fills missing patient-care codes',async()=>{const w=await app();seed(w);w.eval("S.hours[1]['1'][0].c=''");w.chooseWorkLocation('highland-ed');assert.equal(w.eval("S.hours[1]['1'][0].c"),'17013');w.close();});
test('unmapped locations never inherit Highland code and can export only a marked draft',async()=>{const w=await app();seed(w);w.eval("S.hours[1]['1'][0].c='';S.shifts=[{start:'2026-09-24T07:00:00',end:'2026-09-24T17:00:00',name:'San Leandro ED',use:true}]");w.go(3);assert.equal(w.eval("S.hours[1]['1'][0].c"),'');await assert.rejects(()=>w.buildPDF(),/check/i);const result=await w.buildPDF({allowMissingCostCenters:true});assert.equal(result.draft,true);assert.match(result.fname,/DRAFT/);const doc=await w.PDFLib.PDFDocument.load(result.bytes);assert.equal(doc.getPageCount(),20);if(process.env.QA_COST_DRAFT)fs.writeFileSync(process.env.QA_COST_DRAFT,result.bytes);w.close();});
test('location matching preserves explicitly supplied codes and avoids mixed-site guesses',async()=>{const w=await app();seed(w);w.eval("S.hours[1]['1'][0].c='OTHER';S.shifts=[{start:'2026-09-24T07:00:00',end:'2026-09-24T12:00:00',name:'Day ED Highland APP',use:true},{start:'2026-09-24T12:00:00',end:'2026-09-24T17:00:00',name:'Other hospital ED',use:true}]");w.go(3);assert.equal(w.eval("S.hours[1]['1'][0].c"),'OTHER');w.eval("S.hours[1]['1'][0].c=''");w.go(3);assert.equal(w.eval("S.hours[1]['1'][0].c"),'');w.close();});
test('a coding-review draft cannot bypass invalid hours or missing identity',async()=>{const w=await app();seed(w);w.eval("S.hours[1]['1'][0].c='';S.hours[1]['1'][0].h='-1'");await assert.rejects(()=>w.buildPDF({allowMissingCostCenters:true}),/checks/);w.close();});

test('varying-schedule explanation requires a choice and exports the calculated difference',async()=>{
 const w=await app();seed(w);w.document.getElementById('p_hpw').value='30';w.go(3);
 assert.equal(w.document.getElementById('variance').value,'');
 const choice=w.document.getElementById('varianceSchedule');assert.ok(choice,'a ready-to-use reason should be offered');choice.click();
 assert.equal(w.document.getElementById('variance').value,'My shifts vary week to week. This study reports 10.00 hours, 20.00 fewer than my normal 30.00 weekly hours.');
 const {bytes}=await w.buildPDF();const doc=await w.PDFLib.PDFDocument.load(bytes);
 assert.equal(doc.getForm().getTextField('Justification for "Normal Hours Per Week not matching Total Hours').getText(),w.document.getElementById('variance').value);w.close();
});
test('changing hours invalidates a generated explanation but preserves a personally edited reason',async()=>{
 const w=await app();seed(w);w.document.getElementById('p_hpw').value='5';w.go(3);
 const choice=w.document.getElementById('varianceSchedule');assert.ok(choice);choice.click();
 assert.match(w.document.getElementById('variance').value,/5.00 more/);
 w.document.getElementById('p_hpw').value='6';w.go(3);assert.equal(w.document.getElementById('variance').value,'');
 w.document.getElementById('varianceSchedule').click();w.document.getElementById('variance').value='Covered an extra shift.';
 w.document.getElementById('p_hpw').value='8';w.go(3);assert.equal(w.document.getElementById('variance').value,'Covered an extra shift.');w.close();
});
test('generated explanation remains protected against stale totals after reopening',async()=>{
 let w=await app();seed(w);w.document.getElementById('p_hpw').value='30';w.go(3);
 const choice=w.document.getElementById('varianceSchedule');assert.ok(choice);choice.click();
 const stored={};for(const k of Object.keys(w.localStorage))stored[k]=JSON.parse(w.localStorage.getItem(k));w.close();w=await app(stored);
 w.document.getElementById('p_hpw').value='40';assert.equal(w.checks().at(-1).ok,false);assert.equal(w.document.getElementById('variance').value,'');w.close();
});
